export const data = [  
    {
        'id': 1,
        'learn': "Matematika darsligi",
        'learnclass': "6 - Sinf",
        'image': "https://www.oberlo.com/media/1603897950-job.jpg",
        'eyecount': 1666,
    },
    {
        'id': 1,
        'learn': "Matematika darsligi",
        'learnclass': "6 - Sinf",
        'image': "https://www.oberlo.com/media/1603897950-job.jpg",
        'eyecount': 2000,
    },
    {
        'id': 1,
        'learn': "Matematika darsligi",
        'learnclass': "6 - Sinf",
        'image': "https://www.oberlo.com/media/1603897950-job.jpg",
        'eyecount': 2666,
    },
    {
        'id': 1,
        'learn': "Matematika darsligi",
        'learnclass': "6 - Sinf",
        'image': "https://www.oberlo.com/media/1603897950-job.jpg",
        'eyecount': 1000,
    },
    {
        'id': 1,
        'learn': "Matematika darsligi",
        'learnclass': "6 - Sinf",
        'image': "https://www.oberlo.com/media/1603897950-job.jpg",
        'eyecount': 1000,  
    },
    {
        'id': 1,
        'learn': "Matematika darsligi",
        'learnclass': "6 - Sinf",
        'image': "https://www.oberlo.com/media/1603897950-job.jpg",
        'eyecount': 1000,
    },
    {
        'id': 1,  
        'learn': "Matematika darsligi",
        'learnclass': "6 - Sinf",
        'image': "https://www.oberlo.com/media/1603897950-job.jpg",
        'eyecount': 1000,
    },
]