export const datajson = [
  {
    id: 1,
    title: "6 - Sinflar uchun",
    classId: 10,
    state: true,
    usecount: 20,
    scienseCount: 10,
  },
  {
    id: 2,
    title: "7 - Sinflar uchun",
    state: true,
    classId: 11,
    usecount: 20,
    scienseCount: 10,
  },
  {
    id: 3,
    title: "8 - Sinflar uchun",
    state: true,
    classId: 12,
    usecount: 20,
    scienseCount: 10,
  },
  {
    id: 4,
    title: "9 - Sinflar uchun",
    state: true,
    classId: 13,
    usecount: 20,
    scienseCount: 10,
  },
  {
    id: 5,
    title: "10 - Sinflar uchun",
    state: true,
    classId: 14,
    usecount: 20,
    scienseCount: 10,
  },
];
