export const datajson = [
  {
    id: 1,
    categorytitle: "Matematika",
    testcount: 20,
    scienseId: 110,
    classId: 10,
    state: true,
    testcount: 20,
    usecount: 20,
    time: 45,
  },
  {
    id: 2,
    categorytitle: "Ona tili",
    testcount: 20,
    scienseId: 111,
    classId: 10,
    state: true,
    testcount: 20,
    usecount: 20,
    time: 45,
  },
  {
    id: 3,
    categorytitle: "Rus tili",
    testcount: 20,
    scienseId: 112,
    classId: 10,
    state: true,
    testcount: 20,
    usecount: 20,
    time: 45,
  },
  {
    id: 4,
    categorytitle: "Biologiya",
    testcount: 20,
    scienseId: 113,
    classId: 10,
    state: true,
    testcount: 20,
    usecount: 20,
    time: 45,
  },
  {
    id: 5,
    categorytitle: "Biologiya",
    testcount: 20,
    scienseId: 114,
    classId: 11,
    state: true,
    testcount: 20,
    usecount: 20,
    time: 45,
  },
  {
    id: 6,
    categorytitle: "Rus tili",
    testcount: 20,
    scienseId: 115,
    classId: 11,
    state: true,
    testcount: 20,
    usecount: 20,
    time: 45,
  },
  {
    id: 7,
    categorytitle: "Rus tili",
    testcount: 20,
    scienseId: 118,
    classId: 14,
    state: true,
    testcount: 20,
    usecount: 20,
    time: 45,
  },
  {
    id: 8,
    categorytitle: "Induidal Reja",
    testcount: 20,
    scienseId: 119,
    classId: 14,
    state: true,
    testcount: 20,
    usecount: 20,
    time: 45,
  },
];
